# Generated by Django 2.2.8 on 2020-05-01 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('models', '2724_instance_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('send_notifications', models.BooleanField(default=False)),
                ('validate_decay', models.BooleanField(default=False)),
                ('validate_instability', models.BooleanField(default=False)),
                ('validate_vegetation', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='AuthRole',
            fields=[
                ('auth_role_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('permission', models.PositiveIntegerField(choices=[('read_nodegroup', 'Read'), ('write_nodegroup', 'Create/Update'), ('delete_nodegroup', 'Delete'), ('no_access_to_nodegroup', 'No Access')], default='no_access_to_nodegroup')),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.AuthGroup')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.GraphModel')),
            ],
        ),
        migrations.CreateModel(
            name='AreaRole',
            fields=[
                ('area_role_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Value')),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.AuthGroup')),
                ('resource_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_role_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
