# Generated by Django 2.2.8 on 2020-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '2725_arearole_authgroup_authrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroup',
            name='receive_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
