# Generated by Django 2.2.13 on 2020-12-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6700_unique_nodename'),
    ]

    operations = [
        migrations.AddField(
            model_name='authgroup',
            name='is_geodata_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authgroup',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        )
    ]
